import type { BiomeId } from '../types';

export type Realm = 'earth' | 'beyond';

export interface BiomeInfo {
  id: BiomeId;
  /** 'earth' = real places on Earth, 'beyond' = other worlds. */
  realm: Realm;
  name: string;
  /** Native / local flavour title. */
  localName: string;
  region: string;
  culture: string;
  tagline: string;
  description: string;
  unlockLevel: number;
  foodName: string;
  obstacleName: string;
  /** UI accent colours (css). */
  accent: string;
  accentSoft: string;
  /** Background css gradient used behind cards/loading for this biome. */
  cardGradient: string;
}

export const BIOMES: BiomeInfo[] = [
  {
    id: 'karesansui',
    realm: 'earth',
    name: 'Karesansui',
    localName: '枯山水',
    region: 'Kyoto, Japan',
    culture: 'Japanese dry rock garden',
    tagline: 'Rake the silence.',
    description: 'Pale granite gravel raked into still lines. Stones rest in rippled rings while maple shadows sway.',
    unlockLevel: 1,
    foodName: 'Sakura blossom',
    obstacleName: 'Moss stone',
    accent: '#c9a45c',
    accentSoft: '#efe4cc',
    cardGradient: 'linear-gradient(160deg,#efe7d6 0%,#d8ccb2 60%,#b9a887 100%)',
  },
  {
    id: 'erg',
    realm: 'earth',
    name: 'Erg Chebbi',
    localName: 'عرق الشبي',
    region: 'Sahara, Morocco',
    culture: 'Amazigh desert caravan',
    tagline: 'The wind keeps no secrets.',
    description: 'Amber dunes ribbed by the wind. Your trail is slowly swallowed by drifting sand.',
    unlockLevel: 2,
    foodName: 'Golden date',
    obstacleName: 'Sandstone boulder',
    accent: '#e0892f',
    accentSoft: '#f6d9b0',
    cardGradient: 'linear-gradient(160deg,#f3c27a 0%,#d98a3d 55%,#8f4a1f 100%)',
  },
  {
    id: 'lagoon',
    realm: 'earth',
    name: 'Motu Lagoon',
    localName: 'Motu',
    region: 'French Polynesia',
    culture: 'Polynesian island shore',
    tagline: 'The tide forgives everything.',
    description: 'Wet sunset sand, mirror-bright. Waves roll in and wash your story away.',
    unlockLevel: 3,
    foodName: 'Hibiscus',
    obstacleName: 'Coral head',
    accent: '#ff7a6b',
    accentSoft: '#ffd9c8',
    cardGradient: 'linear-gradient(160deg,#ffb38a 0%,#e46b7a 50%,#3d5f8f 100%)',
  },
  {
    id: 'svartsandur',
    realm: 'earth',
    name: 'Svartsandur',
    localName: 'Svartsandur',
    region: 'South coast, Iceland',
    culture: 'Norse volcanic shore',
    tagline: 'Fire sleeps beneath the black.',
    description: 'Black basalt sand under the aurora. Every scar you carve exposes the embers below.',
    unlockLevel: 5,
    foodName: 'Ember crystal',
    obstacleName: 'Basalt column',
    accent: '#ff6a2a',
    accentSoft: '#9fe3d0',
    cardGradient: 'linear-gradient(160deg,#1d2a3a 0%,#121418 55%,#3b1a10 100%)',
  },
  {
    id: 'salar',
    realm: 'earth',
    name: 'Salar',
    localName: 'Salar de Uyuni',
    region: 'Altiplano, Bolivia',
    culture: 'Andean high plateau',
    tagline: 'Walk on the sky.',
    description: 'A crust of salt polygons under a film of water that mirrors the sky. Your wet trail slowly dries.',
    unlockLevel: 7,
    foodName: 'Kantuta flower',
    obstacleName: 'Salt mound',
    accent: '#d6336c',
    accentSoft: '#e6f1fb',
    cardGradient: 'linear-gradient(160deg,#eaf4ff 0%,#bcd7f0 55%,#8aa6c8 100%)',
  },
  {
    id: 'pinksands',
    realm: 'earth',
    name: 'Pink Sands',
    localName: 'Harbour Island',
    region: 'Eleuthera, Bahamas',
    culture: 'Bahamian island, Junkanoo',
    tagline: 'Blush of a million shells.',
    description: 'Sand tinted rose by crushed coral and foraminifera beside turquoise shallows. Your trail turns up the whiter sand beneath, and sea grape shade dances.',
    unlockLevel: 8,
    foodName: 'Conch pearl',
    obstacleName: 'Queen conch',
    accent: '#ff8fab',
    accentSoft: '#ffe3ea',
    cardGradient: 'linear-gradient(160deg,#ffe0e6 0%,#f7a6b8 50%,#3fc1c9 100%)',
  },
  {
    id: 'vaadhoo',
    realm: 'earth',
    name: 'Vaadhoo',
    localName: 'ވާދޫ',
    region: 'Raa Atoll, Maldives',
    culture: 'Maldivian island night',
    tagline: 'The sea of stars.',
    description: 'A moonlit shore where bioluminescent plankton wakes at every touch. Your trail glows electric blue, then slowly fades into the dark.',
    unlockLevel: 10,
    foodName: 'Moon shell',
    obstacleName: 'Driftwood',
    accent: '#3ee7ff',
    accentSoft: '#c7f7ff',
    cardGradient: 'linear-gradient(160deg,#07162b 0%,#0b2d4d 55%,#19c4e0 100%)',
  },
  {
    id: 'dallol',
    realm: 'earth',
    name: 'Dallol',
    localName: 'ዳሎል',
    region: 'Danakil, Ethiopia',
    culture: 'Afar salt caravans',
    tagline: 'Earth that looks like another world.',
    description: 'Acid-yellow sulphur crust, emerald brine pools and white salt terraces in the hottest place on Earth. Break the crust and it hisses with steam.',
    unlockLevel: 12,
    foodName: 'Salt crystal',
    obstacleName: 'Sulphur chimney',
    accent: '#d7e83a',
    accentSoft: '#f4f8c8',
    cardGradient: 'linear-gradient(160deg,#f5f07a 0%,#b9d33a 45%,#2fae8a 100%)',
  },
  {
    id: 'luna',
    realm: 'beyond',
    name: 'Luna',
    localName: 'Mare Tranquillitatis',
    region: 'The Moon',
    culture: 'The space age',
    tagline: 'Every mark lasts a million years.',
    description: 'Grey regolith under a black sky, with Earth hanging over the horizon. There is no air, so shadows are razor sharp and every trail stays forever.',
    unlockLevel: 14,
    foodName: 'Helium-3 crystal',
    obstacleName: 'Ejecta boulder',
    accent: '#cfd8e6',
    accentSoft: '#eef2f8',
    cardGradient: 'linear-gradient(160deg,#050608 0%,#2a2d33 55%,#9aa2ad 100%)',
  },
  {
    id: 'mars',
    realm: 'beyond',
    name: 'Mars',
    localName: 'Jezero Crater',
    region: 'Mars',
    culture: 'The red frontier',
    tagline: 'Rust over ancient stone.',
    description: 'Ochre dust under a butterscotch sky. Your trail scrapes the rust away to show dark basalt, and dust devils wander by and fill it back in.',
    unlockLevel: 16,
    foodName: 'Water-ice core',
    obstacleName: 'Ventifact rock',
    accent: '#e0703a',
    accentSoft: '#f6d2b8',
    cardGradient: 'linear-gradient(160deg,#e9b98a 0%,#c1552a 50%,#4a1d12 100%)',
  },
  {
    id: 'titan',
    realm: 'beyond',
    name: 'Titan',
    localName: 'Shangri-La Dunes',
    region: 'Moon of Saturn',
    culture: 'The methane world',
    tagline: 'Rain that is not water.',
    description: 'Dark hydrocarbon dunes under a thick orange haze, beside the shores of methane lakes. A slow drizzle beads on the sand and softens every trail.',
    unlockLevel: 19,
    foodName: 'Tholin bloom',
    obstacleName: 'Ice cobble',
    accent: '#f0a040',
    accentSoft: '#f8dcae',
    cardGradient: 'linear-gradient(160deg,#f3b35a 0%,#9a5a22 50%,#2a1a10 100%)',
  },
  {
    id: 'kepler',
    realm: 'beyond',
    name: 'Kepler-186f',
    localName: 'Veyra',
    region: 'Exoplanet, 580 light-years away',
    culture: 'An alien garden',
    tagline: 'Two suns, one path.',
    description: 'Violet sand lit by twin suns that cast two shadows, among glowing alien flora and crystal spires. Crystals shatter into light where you pass.',
    unlockLevel: 22,
    foodName: 'Star seed',
    obstacleName: 'Crystal spire',
    accent: '#b57bff',
    accentSoft: '#eadcff',
    cardGradient: 'linear-gradient(160deg,#2a1450 0%,#6a36b8 50%,#ff9ad5 100%)',
  },
];

export const BIOME_BY_ID: Record<BiomeId, BiomeInfo> = Object.fromEntries(
  BIOMES.map((b) => [b.id, b]),
) as Record<BiomeId, BiomeInfo>;
